// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type Cart struct {
	ID     int64
	UserID sql.NullInt64
}

type CartItem struct {
	ProductID sql.NullInt64
	CartID    sql.NullInt64
	Quantity  sql.NullInt64
}

type Product struct {
	ID          int64
	Name        string
	Description sql.NullString
}

type User struct {
	ID      int64
	Name    string
	IsAdmin sql.NullInt64
}
