// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
)

const addCartItem = `-- name: AddCartItem :one
INSERT INTO cart_items (product_id, cart_id, quantity)
    VALUES (?, ?, ?)
RETURNING
    product_id, cart_id, quantity
`

type AddCartItemParams struct {
	ProductID sql.NullInt64
	CartID    sql.NullInt64
	Quantity  sql.NullInt64
}

func (q *Queries) AddCartItem(ctx context.Context, arg AddCartItemParams) (CartItem, error) {
	row := q.db.QueryRowContext(ctx, addCartItem, arg.ProductID, arg.CartID, arg.Quantity)
	var i CartItem
	err := row.Scan(&i.ProductID, &i.CartID, &i.Quantity)
	return i, err
}

const createAdminUser = `-- name: CreateAdminUser :one
INSERT INTO users (name, is_admin)
    VALUES (?, 1)
RETURNING
    id, name, is_admin
`

func (q *Queries) CreateAdminUser(ctx context.Context, name string) (User, error) {
	row := q.db.QueryRowContext(ctx, createAdminUser, name)
	var i User
	err := row.Scan(&i.ID, &i.Name, &i.IsAdmin)
	return i, err
}

const createCart = `-- name: CreateCart :one
INSERT INTO carts (user_id)
    VALUES (?)
RETURNING
    id, user_id
`

func (q *Queries) CreateCart(ctx context.Context, userID sql.NullInt64) (Cart, error) {
	row := q.db.QueryRowContext(ctx, createCart, userID)
	var i Cart
	err := row.Scan(&i.ID, &i.UserID)
	return i, err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (name, description)
    VALUES (?, ?)
RETURNING
    id, name, description
`

type CreateProductParams struct {
	Name        string
	Description sql.NullString
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, createProduct, arg.Name, arg.Description)
	var i Product
	err := row.Scan(&i.ID, &i.Name, &i.Description)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (name)
    VALUES (?)
RETURNING
    id, name, is_admin
`

func (q *Queries) CreateUser(ctx context.Context, name string) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, name)
	var i User
	err := row.Scan(&i.ID, &i.Name, &i.IsAdmin)
	return i, err
}
