CREATE TABLE IF NOT EXISTS items (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  name VARCHAR NOT NULL UNIQUE,
  description TEXT
);

CREATE TABLE IF NOT EXISTS users (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  name VARCHAR NOT NULL
  is_admin INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS carts (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  item_id INTEGER,
  user_id INTEGER,
  FOREIGN KEY (item_id) REFERENCES items(item_id),
  FOREIGN KEY (user_id) REFERENCES users(user_id)
);

